version: '3.9'

services:
  django:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./django:/django
      - ./data/web:/vol/web
    environment:
      - DJANGO_SECRET_KEY=devsecretkey
      - DJANGO_DEBUG=1
      - DB_HOST=db
      - DB_NAME=django_db
      - DB_USER=django
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=changeme